spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis_test_db?useSSL=false&autoReconnect=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678

mybatis:
#  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.orcl.mybatis.pojo
  configuration:
    cache-enabled: true
    use-generated-keys: true
    default-executor-type: REUSE
    use-actual-param-name: true